### ISSUE TITLE
Quy trình thực hiện

### ISSUE THREAD

**Issue by manhtuan07081998** [manhtuan07081998/ADS-block-with-docker#1]
**[1]. Cài docker:**
### Cập nhật OS
```sudo apt update && sudo apt upgrade -y```

### Tải và cài docker
```curl -sSL https://get.docker.com | sh ```

### Add user vào group
```sudo usermod -aG docker $USER ```

### Kiểm tra docker và chạy thử helloworld
```
docker version
docker run hello-world
```

### Tải và cài: Docker Compose
```
mkdir -p ~/.docker/cli-plugins
curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-aarch64 -o ~/.docker/cli-plugins/docker-compose
```

###Cấp quyền chạy
```chmod +x ~/.docker/cli-plugins/docker-compose```

### Kiểm tra phiên bản
```docker compose version```

**[2]. Tạo docker chạy ADS**

### Tạo file docker-compose.yml thư mục adguardhome để cấu hình dịch vụ
```
cd ~
mkdir adguardhome
cd adguardhome
nano docker-compose.yml
```

### Nhập nội dung này vào file và lưu lại
```
          version: "2"
          services:
            adguardhome:
              image: adguard/adguardhome
              container_name: adguardhome
              ports:
                - 53:53/tcp
                - 53:53/udp
                - 784:784/udp
                - 853:853/tcp
                - 3000:3000/tcp
                - 8080:80/tcp
              volumes:
                - ./workdir:/opt/adguardhome/work
                - ./confdir:/opt/adguardhome/conf
              restart: unless-stopped
```
### Kích hoạt Docker compose chạy AdGuard Home (sẽ chạy tự động nếu sử dụng compose)
`sudo docker compose up -d`

**[3]. Cấu hình ADS**
--> Vào địa chỉ ip của thiết bị tại port 3000
--> Chỉ cần cài đặt user và password còn lại next hết
--> Vào lại địa chỉ của thiết bị tại port 8080
--> Vào mục setting --> DNS setting --> thay bằng "https://dns.cloudflare.com/dns-query"
--> Vào Filters --> DNS blocklists --> Thêm các list sau: 

- AdGuard DNS filter
- AdGuard DNS Popup Hosts filter
- HaGeZi’s Pro++ Blocklist
- Steven Black’s List
- OISD Blocklist Big

**[4]. Cấu hình thiết bị sử dụng mạng**
--> Cấu hình DNS1 của thiết bị đến IP của ADS server

**[5]. Cấu hình IP tĩnh cho ADS server (DDNS)**

### tạo file config
```sudo nano /etc/systemd/network/10-eth0.network```

### Nội dung file
```
[Match]
Name=eth0 #thay bằng wlan0 nếu sử dụng wifi

[Network]
Address=192.168.1.100/24 #IP tĩnh muốn đặt
Gateway=192.168.1.1 #IP gateway
DNS=8.8.8.8
```

### Kích hoạt systemd-networkd
```
sudo systemctl enable systemd-networkd
sudo systemctl restart systemd-networkd
```

### Thay đổi tài khoản mật khẩu
sử dụng tạo mã Htpasswd để băm ra mã thay thế tại mục user của file `AdGuardHome.yaml` thay bằng mã HASH tạo bằng trình tạo sẵn tại "https://hostingcanada.org/htpasswd-generator/"

Copyright by https://thuanbui.me/adguard-home/
